# Site settings
title: Intraspecto
header-img: img/home-bg.png
email: binnylewis@gmail.com
copyright_name: alex2binny
description: > # this means to ignore newlines until "baseurl:"
  Introspective thoughts about the world, code, family and more.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: alex2binny
github_username:  alex2binny
learn_profile: alex2binny
email_username: binnylewis@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
